### ISSUE TITLE
spatial plots are 180 degrees flipped

### ISSUE THREAD

**Issue by lepmik** [CINPLA/exana-legacy#4]

**Comment by alejoe91** [comment]
The openephys tracking (I don't know about the axona but I guess it's the same) has the (0,0) in the upper left corner.
In the pyopenephys.py I corrected it by:
`coord = np.array([x, 1-y])`
where x and y are the [0,1] arrays ;)

**Comment by lepmik** [comment]
The problem with this solution is that you assume `y <= 1`, thus if you e.g. have rounding errors etc., you get negative values in coord.

Therefore I think it is safer to annotate the origin in the tracker output and deal with the visualization later e.g. 

```python
if origin == 'upper':
    ax.invert_yaxis()
```
