### ISSUE TITLE
last index in vector

### ISSUE THREAD

**Issue by tristanstoeber** [CINPLA/exana-legacy#7]
Hey Mikkel,

In the spatial rate map function of fields, you are skipping the last index of x
https://github.com/CINPLA/exana/blob/dev/exana/tracking/fields.py#L69-71

``` python
    for n in range(len(x) - 1):
        spike_pos[ix[n], iy[n]] += spikes_in_bin[n]
        time_pos[ix[n], iy[n]] += time_in_bin[n]
```
Why are you doing this? Arent you missing the last bin with that?

Best,
Tristan

**Comment by lepmik** [comment]
Yeah, thanks, that was a leftover from a previous version, where I did it to omit an indexerror. can you fix it?

**Comment by tristanstoeber** [comment]
fixed
